// <auto-generated />
using System;
using Backend.Domain.Enum;
using Backend.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200217192031_ExerciseOrder")]
    partial class ExerciseOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ContainsMedia")
                        .HasColumnType("bit");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FileSizeInBytes")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("S3Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SeenAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Dashboard.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Dashboard.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Dashboard.TrackItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Component")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParamsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackItems");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Dashboard.TrackItemParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JsonParams")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TrackItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrackItemId")
                        .IsUnique()
                        .HasFilter("[TrackItemId] IS NOT NULL");

                    b.ToTable("TrackItemParams");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ExerciseType.ExerciseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresBodyweight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiresReps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("RequiresSets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("RequiresTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiresWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("ExerciseTypes");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ExerciseType.ExerciseTypeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Show")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.HasIndex("TagId");

                    b.ToTable("ExerciseTypeTags");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ExerciseType.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("TagGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TagGroupId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ExerciseType.TagGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HexBackground")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("#fef6f9");

                    b.Property<string>("HexColor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("#616161");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("TagGroups");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Media.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FtpFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Notification.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Subtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SystemNotification")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProgressTracking.Max.ExerciseMax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExerciseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("IpfPoints")
                        .HasColumnType("float");

                    b.Property<double>("Max")
                        .HasColumnType("float");

                    b.Property<double>("WilksScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("ExerciseMax");
                });


            modelBuilder.Entity("Backend.Domain.Entities.TrainingLog.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Backend.Domain.Entities.TrainingLog.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AverageVelocity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Intensity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProjectedMax")
                        .HasColumnType("float");

                    b.Property<double>("Reps")
                        .HasColumnType("float");

                    b.Property<double>("Rir")
                        .HasColumnType("float");

                    b.Property<double>("Rpe")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Backend.Domain.Entities.TrainingLog.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTrained")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NoteRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Male");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrialDuration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15);

                    b.Property<Guid>("UserSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserSettingId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("AccountType").HasValue("User");
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.NotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReceiveMail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ReceiveNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("UserSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserSettingId");

                    b.ToTable("NotificationSetting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("394d7ead-e304-4241-bbb5-e367552e2158"),
                            NotificationType = "TrainingCreated",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("ef44ac97-374b-437f-b3ec-b805628128a0")
                        },
                        new
                        {
                            Id = new Guid("145bb8ea-9b09-4249-97db-5931f86217bb"),
                            NotificationType = "NoteAdded",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("ef44ac97-374b-437f-b3ec-b805628128a0")
                        },
                        new
                        {
                            Id = new Guid("166675c9-c271-41ba-b309-31433592123a"),
                            NotificationType = "MediaAdded",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("ef44ac97-374b-437f-b3ec-b805628128a0")
                        },
                        new
                        {
                            Id = new Guid("980db46f-4d21-4526-b36c-c5d86d52ba32"),
                            NotificationType = "ImportFinished",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("ef44ac97-374b-437f-b3ec-b805628128a0")
                        },
                        new
                        {
                            Id = new Guid("a6edcf9c-6dbf-45ce-8889-d9effc3b1081"),
                            NotificationType = "TrainingCreated",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("4c91d66e-6c0a-41d8-8dfc-12c427be8d77")
                        },
                        new
                        {
                            Id = new Guid("49d74778-872f-4744-8297-41c9ecc4e88b"),
                            NotificationType = "NoteAdded",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("4c91d66e-6c0a-41d8-8dfc-12c427be8d77")
                        },
                        new
                        {
                            Id = new Guid("04db3199-1165-4e47-aafe-73ac6494f3fb"),
                            NotificationType = "MediaAdded",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("4c91d66e-6c0a-41d8-8dfc-12c427be8d77")
                        },
                        new
                        {
                            Id = new Guid("810d105a-b55c-4760-a886-9b3d3d5ac18b"),
                            NotificationType = "ImportFinished",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("4c91d66e-6c0a-41d8-8dfc-12c427be8d77")
                        },
                        new
                        {
                            Id = new Guid("6b94b059-4b4c-4c83-b2e0-08588edea51e"),
                            NotificationType = "TrainingCreated",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("b18cd95a-b2e4-44e8-810d-0d349afbc244")
                        },
                        new
                        {
                            Id = new Guid("f34b3bd4-6c69-4bc0-a77c-0398b9881955"),
                            NotificationType = "NoteAdded",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("b18cd95a-b2e4-44e8-810d-0d349afbc244")
                        },
                        new
                        {
                            Id = new Guid("80c36ed2-e7da-4ae4-bdb5-dbfbcddbc012"),
                            NotificationType = "MediaAdded",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("b18cd95a-b2e4-44e8-810d-0d349afbc244")
                        },
                        new
                        {
                            Id = new Guid("5ee5029a-51b9-497d-879b-9623b37b648e"),
                            NotificationType = "ImportFinished",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("b18cd95a-b2e4-44e8-810d-0d349afbc244")
                        },
                        new
                        {
                            Id = new Guid("34f7db7f-329d-4c6c-9a19-94ba6d0f7d5d"),
                            NotificationType = "TrainingCreated",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("6dc94886-2abc-4831-b168-dbb5dc1c5322")
                        },
                        new
                        {
                            Id = new Guid("8e8b28d8-371c-4718-bd2b-3aad41ed72ef"),
                            NotificationType = "NoteAdded",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("6dc94886-2abc-4831-b168-dbb5dc1c5322")
                        },
                        new
                        {
                            Id = new Guid("fb60ba88-99e0-4fef-8b08-7f07d66911c8"),
                            NotificationType = "MediaAdded",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("6dc94886-2abc-4831-b168-dbb5dc1c5322")
                        },
                        new
                        {
                            Id = new Guid("85b34866-7cc3-4e7d-ac95-de293e4d344c"),
                            NotificationType = "ImportFinished",
                            ReceiveMail = false,
                            ReceiveNotification = false,
                            UserSettingId = new Guid("6dc94886-2abc-4831-b168-dbb5dc1c5322")
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MainDashboardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RpeSystem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Rpe");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Light");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Metric");

                    b.Property<bool>("UseRpeSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("MainDashboardId")
                        .IsUnique()
                        .HasFilter("[MainDashboardId] IS NOT NULL");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef44ac97-374b-437f-b3ec-b805628128a0"),
                            ApplicationUserId = new Guid("277b27f5-637e-422f-9779-9805c628c709"),
                            RpeSystem = "Rpe",
                            Theme = "Light",
                            UnitSystem = "Imperial",
                            UseRpeSystem = false
                        },
                        new
                        {
                            Id = new Guid("4c91d66e-6c0a-41d8-8dfc-12c427be8d77"),
                            ApplicationUserId = new Guid("a66d7de8-2d0f-4223-8618-3a1f81474e4f"),
                            RpeSystem = "Rpe",
                            Theme = "Light",
                            UnitSystem = "Imperial",
                            UseRpeSystem = false
                        },
                        new
                        {
                            Id = new Guid("b18cd95a-b2e4-44e8-810d-0d349afbc244"),
                            ApplicationUserId = new Guid("e79c9142-e16f-4b9e-97c3-56965ad1c709"),
                            RpeSystem = "Rpe",
                            Theme = "Light",
                            UnitSystem = "Imperial",
                            UseRpeSystem = false
                        },
                        new
                        {
                            Id = new Guid("6dc94886-2abc-4831-b168-dbb5dc1c5322"),
                            ApplicationUserId = new Guid("e4e72ef1-a9a0-45ae-9aa7-231b47879394"),
                            RpeSystem = "Rpe",
                            Theme = "Light",
                            UnitSystem = "Imperial",
                            UseRpeSystem = false
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.Admin", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.User.ApplicationUser");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("277b27f5-637e-422f-9779-9805c628c709"),
                            AccountType = "User",
                            Active = false,
                            CreatedOn = new DateTime(2020, 2, 17, 19, 20, 30, 992, DateTimeKind.Utc).AddTicks(9280),
                            CustomerId = "cus_FLi7gZv8w0j0GB",
                            Email = "admin@trainingcompanion.com",
                            FirstName = "Admin",
                            Gender = "Male",
                            LastModified = new DateTime(2020, 2, 17, 19, 20, 30, 992, DateTimeKind.Utc).AddTicks(9879),
                            LastName = "",
                            PasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            TrialDuration = 0,
                            UserSettingId = new Guid("ef44ac97-374b-437f-b3ec-b805628128a0"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.Athlete", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.User.ApplicationUser");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CoachId");

                    b.HasDiscriminator().HasValue("Athlete");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a66d7de8-2d0f-4223-8618-3a1f81474e4f"),
                            AccountType = "User",
                            Active = false,
                            CreatedOn = new DateTime(2020, 2, 17, 19, 20, 30, 993, DateTimeKind.Utc).AddTicks(2377),
                            Email = "athlete@trainingcompanion.com",
                            FirstName = "Athlete",
                            Gender = "Male",
                            LastModified = new DateTime(2020, 2, 17, 19, 20, 30, 993, DateTimeKind.Utc).AddTicks(2393),
                            LastName = "",
                            PasswordHash = "23a1f74bc589fe525387f8d2c40f1e552a564fe5de00af935bb7a0592fc976c6",
                            TrialDuration = 0,
                            UserSettingId = new Guid("4c91d66e-6c0a-41d8-8dfc-12c427be8d77"),
                            Username = "athlete",
                            CoachId = new Guid("e79c9142-e16f-4b9e-97c3-56965ad1c709")
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.Coach", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.User.ApplicationUser");

                    b.HasDiscriminator().HasValue("Coach");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e79c9142-e16f-4b9e-97c3-56965ad1c709"),
                            AccountType = "User",
                            Active = false,
                            CreatedOn = new DateTime(2020, 2, 17, 19, 20, 30, 993, DateTimeKind.Utc).AddTicks(5494),
                            CustomerId = "cus_FHk5RepADdfm5H",
                            Email = "coach@trainingcompanion.com",
                            FirstName = "Coach",
                            Gender = "Male",
                            LastModified = new DateTime(2020, 2, 17, 19, 20, 30, 993, DateTimeKind.Utc).AddTicks(5498),
                            LastName = "",
                            PasswordHash = "e0f167bc84b881bc06f6884fb48e02f41dfc5579e25489db6c6bde238e4aed15",
                            TrialDuration = 0,
                            UserSettingId = new Guid("b18cd95a-b2e4-44e8-810d-0d349afbc244"),
                            Username = "coach"
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.SoloAthlete", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.User.ApplicationUser");

                    b.HasDiscriminator().HasValue("SoloAthlete");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4e72ef1-a9a0-45ae-9aa7-231b47879394"),
                            AccountType = "User",
                            Active = false,
                            CreatedOn = new DateTime(2020, 2, 17, 19, 20, 30, 993, DateTimeKind.Utc).AddTicks(3241),
                            Email = "solo.athlete@trainingcompanion.com",
                            FirstName = "Solo",
                            Gender = "Male",
                            LastModified = new DateTime(2020, 2, 17, 19, 20, 30, 993, DateTimeKind.Utc).AddTicks(3245),
                            LastName = "Athlete",
                            PasswordHash = "304301ea5935cd1d38e55206e09eebcfe95fcb56f96ddf0ef2d8557a295728c8",
                            TrialDuration = 0,
                            UserSettingId = new Guid("6dc94886-2abc-4831-b168-dbb5dc1c5322"),
                            Username = "soloathlete"
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User.ApplicationUser", "Sender")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Dashboard.Track", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Dashboard.Dashboard", "Dashboard")
                        .WithMany("Tracks")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Dashboard.TrackItem", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Dashboard.Track", "Track")
                        .WithMany("Items")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Dashboard.TrackItemParams", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Dashboard.TrackItem", "TrackItem")
                        .WithOne("Params")
                        .HasForeignKey("Backend.Domain.Entities.Dashboard.TrackItemParams", "TrackItemId");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ExerciseType.ExerciseType", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithMany("ExerciseTypes")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.ExerciseType.ExerciseTypeTag", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ExerciseType.ExerciseType", "ExerciseType")
                        .WithMany("Properties")
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.ExerciseType.Tag", "Tag")
                        .WithMany("ExerciseTypeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.ExerciseType.Tag", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ExerciseType.TagGroup", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.ExerciseType.TagGroup", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithMany("TagGroups")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Media.MediaFile", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithMany("MediaFiles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.TrainingLog.Exercise", "Exercise")
                        .WithMany("Media")
                        .HasForeignKey("ExerciseId");

                    b.HasOne("Backend.Domain.Entities.TrainingLog.Training", "Training")
                        .WithMany("Media")
                        .HasForeignKey("TrainingId");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Notification.Notification", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User.ApplicationUser", "Receiver")
                        .WithMany("ReceivedNotifications")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Domain.Entities.User.ApplicationUser", "Sender")
                        .WithMany("SentNotifications")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProgressTracking.Max.ExerciseMax", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ExerciseType.ExerciseType", "ExerciseType")
                        .WithMany("ExerciseMaxes")
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.TrainingLog.Exercise", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ExerciseType.ExerciseType", "ExerciseType")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.TrainingLog.Training", "Training")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.TrainingLog.Set", b =>
                {
                    b.HasOne("Backend.Domain.Entities.TrainingLog.Exercise", "Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.TrainingLog.Training", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithMany("Trainings")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.ApplicationUser", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User.UserSetting", "UserSetting")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Backend.Domain.Entities.User.ApplicationUser", "UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.NotificationSetting", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User.UserSetting", "UserSetting")
                        .WithMany("NotificationSettings")
                        .HasForeignKey("UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.UserSetting", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Dashboard.Dashboard", "MainDashboard")
                        .WithOne("UserSetting")
                        .HasForeignKey("Backend.Domain.Entities.User.UserSetting", "MainDashboardId");
                });

            modelBuilder.Entity("Backend.Domain.Entities.User.Athlete", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User.Coach", "Coach")
                        .WithMany("Athletes")
                        .HasForeignKey("CoachId");
                });
#pragma warning restore 612, 618
        }
    }
}
