using AutoMapper;
using Backend.Domain;
using Backend.Domain.Entities.Exercises;
using Backend.Infrastructure.Exceptions;
using MediatR;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Backend.Business.Exercises.ExerciseTypeRequests.Create
{
    public class CreateExerciseTypeRequestHandler :
        IRequestHandler<CreateExerciseTypeRequest, ExerciseType>
    {
        private readonly IApplicationDbContext _context;
        private readonly IMapper _mapper;

        public CreateExerciseTypeRequestHandler(IApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public async Task<ExerciseType> Handle(CreateExerciseTypeRequest request, CancellationToken cancellationToken)
        {
            try
            {
                var exerciseType = _mapper.Map<ExerciseType>(request);
                // take care of this which would normally be generated by DB.. but we need to know it in advance
                exerciseType.Code = Guid.NewGuid().ToString();

                var createdEntity = CreateExerciseType(exerciseType, request.ApplicationUserId);

                // athlete needs to have the same record
                var user = await _context.Coaches.Include(x => x.Athletes).FirstOrDefaultAsync(x => x.Id == request.ApplicationUserId, cancellationToken);
                if (user != null)
                {
                    foreach (var athlete in user.Athletes)
                    {
                        CreateExerciseType(exerciseType, athlete.Id);
                    }
                }

                await _context.SaveChangesAsync(cancellationToken);

                // load tags for display
                foreach (var prop in createdEntity.Properties)
                {
                    // tag must be loaded.. so we can access parent tag group
                    await _context.Entry(prop).Reference(x => x.Tag).LoadAsync(cancellationToken);
                    await _context.Entry(prop.Tag).Reference(x => x.TagGroup).LoadAsync(cancellationToken);
                }

                return createdEntity;
            }
            catch (Exception e)
            {
                throw new CreateFailureException(nameof(ExerciseType), e);
            }
        }

        private ExerciseType CreateExerciseType(ExerciseType exerciseType, Guid userId)
        {
            var entityToCreate = _mapper.Map<ExerciseType>(exerciseType);
            entityToCreate.ApplicationUserId = userId;

            _context.ExerciseTypes.Add(entityToCreate);

            return entityToCreate;
        }
    }
}