version: "3.4"

services:
    frontend:
        build: 
            context: .
            dockerfile: Dockerfiles/Dockerfile-frontend
        ports:
            - "5003:443"
            - "5002:80"
        depends_on:
        - backend
    backend:
        build: 
            context: .
            dockerfile: Dockerfiles/Dockerfile-backend
        ports:
            - "5001:443"
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Release
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssword1
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/trainingcompanion.pfx
        volumes:
            - ./certificate/.aspnet/https/:/https/
        depends_on:
        - sqlserver
    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1733:1433"
        environment:
            SA_PASSWORD: "P@ssword1"
            ACCEPT_EULA: "Y"