version: "3.4"

services:
    webapp:
        build: .
        ports:
            - "5001:443"
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Release
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=GornjaSoba34a
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/trainingcompanion.pfx
        volumes:
            - ./certificate/.aspnet/https/:/https/
        depends_on:
        - sqlserver
    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1733:1433"
        environment:
            SA_PASSWORD: "GornjaSoba34a"
            ACCEPT_EULA: "Y"